#### Data set descriptive statistics

Dataset: 
 
 - _music_clean.csv_ 

Author: Luis Sergio Pastrana Lemus  
Date: 2025-04-23

# Exploratory Data Analysis (Descriptive Statistics) – Music Activity Dataset

## __1. Libraries__

In [1]:
from IPython.display import display, HTML
import os
import pandas as pd
from pathlib import Path
import sys

# Define project root dynamically, gets the current directory from whick the notebook belongs and moves one level upper
project_root = Path.cwd().parent

# Add src to sys.path if it is not already
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Import function directly (more controlled than import *)
from src import *

## __2. Path to Data file__

In [2]:
# Build route to data file and upload
data_file_path = project_root / "data" / "processed"
df_music_clean = load_dataset_from_csv(data_file_path, "music_clean.csv", sep=',', header='infer', keep_default_na=False)

# data_file_path = project_root / "data" / "processed" / "music_activity"
# df_music_activity_city = load_dataset_from_csv(data_file_path, ".csv", sep=',', header='infer')

## __3. Exploratory Data Analysis__

### 3.0 Casting Data Types

#### 3.0.1 Casting to category datatype

In [3]:
# Casting to category dtype 
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['genre'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['city'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['day'])

#### 3.0.2 Casting to datetime data type

In [4]:
# Casting to datetime dtype 
df_music_clean = cast_datatypes(df_music_clean, 'datetime', date_format="%H:%M:%S", c_include=['time'])

In [5]:
df_music_clean

,userid,track,artist,genre,city,time,day
0,FFB692EC,kamigata_to_boots,the_mass_missile,rock,shelbyville,20:28:33,wednesday
1,55204538,delayed_because_of_accident,andreas_ronnberg,rock,springfield,14:07:09,friday
2,20EC38,funiculi_funicula,mario_lanza,pop,shelbyville,20:58:07,wednesday
3,A3DD03C9,dragons_in_the_sunset,fire_ice,folk,shelbyville,08:37:09,monday
4,E2DC1FAE,soul_people,space_echo,dance,springfield,08:34:34,monday
...,...,...,...,...,...,...,...
59957,729CBB09,my_name,mclean,rnb,springfield,13:32:28,wednesday
59958,D08D4A55,maybe_one_day_feat_black_spade,blu_exile,hiphop,shelbyville,10:00:00,monday
59959,C5E3A0D5,jalopiina,unknown,industrial,springfield,20:09:26,friday
59960,321D0506,freight_train,chas_mcdevitt,rock,springfield,21:43:59,friday
59961,3A64EF84,tell_me_sweet_little_lies,monica_lopez,country,springfield,21:59:46,friday

In [6]:
df_music_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59962 entries, 0 to 59961
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userid  59962 non-null  object
 1   track   59962 non-null  object
 2   artist  59962 non-null  object
 3   genre   59962 non-null  category
 4   city    59962 non-null  category
 5   time    59962 non-null  object
 6   day     59962 non-null  category
dtypes: category(3), object(4)
memory usage: 2.1+ MB

In [7]:
type(df_music_clean['time'].iloc[0])

datetime.time

### 3.1 Descriptive Statistics

In [8]:
# Descriptive statistics for df_music_clean dataset
df_music_clean.describe(include='all')

          userid  track   artist  genre         city      time     day
count      59962  59962    59962  59962        59962     59962   59962
unique     41318  38777    37676    264            2     20299       3
top     E8339398  brand  unknown    pop  springfield  21:51:22  friday
freq          43    127     5854   8176        41854        12   21464

In [9]:
# Descriptive analysis for 'track' column
display(HTML(f"> Most frequent data value within ['track'] column: <b>{df_music_clean['track'].mode()[0]}</b>"))

In [10]:
df_music_clean['track'].value_counts()

track
brand                          127
so_long                        110
going_back                      90
moscow_calling                  87
all_for_you                     84
                              ...
shout_to_the_lord                1
feels_like_saving_the_world      1
welcome_to_zombietown            1
slaves_of_fear                   1
make_love_whenever_you_can       1
Name: count, Length: 38777, dtype: int64

In [14]:
# Histogram for 'track' column
plot_cualitative_histogram_plotlypx(df_music_clean['track'], color="grey", title="Histogram for ['track'] column", xlabel="Tracks", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [15]:
# Descriptive analysis for 'artist' column
display(HTML(f"> Most frequent data value within ['artist'] column: <b>{df_music_clean.loc[(df_music_clean['artist'] != 'unknown'), 'artist'].mode()[0]}</b>"))

In [16]:
df_music_clean['artist'].value_counts()

artist
unknown               5854
kartvelli              127
malfa                  109
real_bodrit             90
the_seasons             79
                      ...
outlandish               1
king_hot                 1
david_erwin              1
om_ovnimoon              1
marianne_faithfull       1
Name: count, Length: 37676, dtype: int64

In [25]:
# Histogram for 'artist' column
plot_cualitative_histogram_plotlypx(df_music_clean.loc[(df_music_clean['artist'] != 'unknown'), 'artist'], color="grey", title="Histogram for ['artist'] column", xlabel="Artists", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [19]:
# Descriptive analysis for 'genre' column
display(HTML(f"> Most frequent data value within ['genre'] column: <b>{df_music_clean['genre'].mode()[0]}</b>"))

In [20]:
df_music_clean['genre'].value_counts()

genre
pop              8176
dance            6334
rock             5769
electronic       5518
hiphop           3020
                 ...
specialty           1
taraftar            1
tanzorchester       1
synthpop            1
acid                1
Name: count, Length: 264, dtype: int64

In [26]:
# Histogram for 'genre' column
plot_cualitative_histogram_plotlypx(df_music_clean['genre'], color="grey", title="Histogram for ['genre'] column", xlabel="Genres", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [21]:
# Descriptive analysis for 'city' column
display(HTML(f"> Most frequent data value within ['city'] column: <b>{df_music_clean['city'].mode()[0]}</b>"))

In [22]:
df_music_clean['city'].value_counts()

city
springfield    41854
shelbyville    18108
Name: count, dtype: int64

In [28]:
# Histogram for 'city' column
plot_cualitative_histogram_plotlypx(df_music_clean['city'], color="grey", title="Histogram for ['city'] column", xlabel="Cities", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=0, rotation_y=0, top_n=None)

In [29]:
# Descriptive analysis for 'time' column
display(HTML(f"> Most frequent data value within ['time'] column: <b>{df_music_clean['time'].mode()[0]}</b>"))

In [30]:
df_music_clean['time'].value_counts()

time
21:51:22    12
09:25:10    12
08:14:07    12
20:29:42    11
20:18:55    10
            ..
14:05:30     1
14:38:30     1
13:21:33     1
20:03:28     1
13:56:26     1
Name: count, Length: 20299, dtype: int64

In [31]:
# Histogram for 'time' column
plot_cualitative_histogram_plotlypx(df_music_clean['time'], color="grey", title="Histogram for ['time'] column", xlabel="Time", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [32]:
# Descriptive analysis for 'day' column
display(HTML(f"> Most frequent data value within ['day'] column: <b>{df_music_clean['day'].mode()[0]}</b>"))

In [33]:
df_music_clean['day'].value_counts()

day
friday       21464
monday       20792
wednesday    17706
Name: count, dtype: int64

In [34]:
# Histogram for 'day' column
plot_cualitative_histogram_plotlypx(df_music_clean['day'], color="grey", title="Histogram for ['day'] column", xlabel="Days", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=0, rotation_y=0, top_n=None)