#### Data set descriptive statistics

Dataset: 
 
 - _music_clean.csv_ 
 - _music_location.csv_
 - _music_location_datetime_.csv

Author: Luis Sergio Pastrana Lemus  
Date: 2025-04-23

# Exploratory Data Analysis (Descriptive Statistics) – Music Activity Dataset

## __1. Libraries__

In [1]:
from IPython.display import display, HTML
import os
import pandas as pd
from pathlib import Path
import plotly.express as px
import sys

# Define project root dynamically, gets the current directory from whick the notebook belongs and moves one level upper
project_root = Path.cwd().parent

# Add src to sys.path if it is not already
if str(project_root) not in sys.path:
    sys.path.append(str(project_root))

# Import function directly (more controlled than import *)
from src import *

## __2. Path to Data file__

In [2]:
# Build route to data file and upload
data_file_path = project_root / "data" / "processed"
df_music_clean = load_dataset_from_csv(data_file_path, "music_clean.csv", sep=',', header='infer', keep_default_na=False)
df_music_location = load_dataset_from_csv(data_file_path, "music_location.csv", sep=',', header='infer', keep_default_na=False)
df_music_loc_dt = load_dataset_from_csv(data_file_path, "music_location_datetime.csv", sep=',', header='infer', keep_default_na=False)

## __3. Casting Data Types__

### **3.1** Casting to category datatype

In [3]:
# Casting to category dtype 
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['genre'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['city'])
df_music_clean = cast_datatypes(df_music_clean, 'category', c_include=['day'])

### **3.2** Casting to datetime data type

In [4]:
# Casting to datetime dtype 
df_music_clean = cast_datatypes(df_music_clean, 'datetime', date_format="%H:%M:%S", c_include=['time'])

In [5]:
df_music_clean

,userid,track,artist,genre,city,time,day
0,FFB692EC,kamigata_to_boots,the_mass_missile,rock,shelbyville,20:28:33,wednesday
1,55204538,delayed_because_of_accident,andreas_ronnberg,rock,springfield,14:07:09,friday
2,20EC38,funiculi_funicula,mario_lanza,pop,shelbyville,20:58:07,wednesday
3,A3DD03C9,dragons_in_the_sunset,fire_ice,folk,shelbyville,08:37:09,monday
4,E2DC1FAE,soul_people,space_echo,dance,springfield,08:34:34,monday
...,...,...,...,...,...,...,...
59957,729CBB09,my_name,mclean,rnb,springfield,13:32:28,wednesday
59958,D08D4A55,maybe_one_day_feat_black_spade,blu_exile,hiphop,shelbyville,10:00:00,monday
59959,C5E3A0D5,jalopiina,unknown,industrial,springfield,20:09:26,friday
59960,321D0506,freight_train,chas_mcdevitt,rock,springfield,21:43:59,friday
59961,3A64EF84,tell_me_sweet_little_lies,monica_lopez,country,springfield,21:59:46,friday

In [6]:
df_music_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59962 entries, 0 to 59961
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userid  59962 non-null  object
 1   track   59962 non-null  object
 2   artist  59962 non-null  object
 3   genre   59962 non-null  category
 4   city    59962 non-null  category
 5   time    59962 non-null  object
 6   day     59962 non-null  category
dtypes: category(3), object(4)
memory usage: 2.1+ MB

In [7]:
type(df_music_clean['time'].iloc[0])

datetime.time

## __4. Exploratory Data Analysis__

### **4.1** Descriptive Statistics

In [8]:
# Descriptive statistics for df_music_clean dataset
df_music_clean.describe(include='all')

          userid  track   artist  genre         city      time     day
count      59962  59962    59962  59962        59962     59962   59962
unique     41318  38777    37676    264            2     20299       3
top     E8339398  brand  unknown    pop  springfield  21:51:22  friday
freq          43    127     5854   8176        41854        12   21464

#### **4.1.1** Descriptive statistics for Qualitative Data

In [9]:
# Descriptive analysis for 'track' column
display(HTML(f"> Most frequent data value within ['track'] column: <b>{df_music_clean['track'].mode()[0]}</b>"))

In [10]:
df_music_clean['track'].value_counts()

track
brand                          127
so_long                        110
going_back                      90
moscow_calling                  87
all_for_you                     84
                              ...
shout_to_the_lord                1
feels_like_saving_the_world      1
welcome_to_zombietown            1
slaves_of_fear                   1
make_love_whenever_you_can       1
Name: count, Length: 38777, dtype: int64

In [ ]:
# Histogram for 'track' column
plot_cualitative_histogram_plotlypx(df_music_clean['track'], color="grey", title="Histogram for ['track'] column", xlabel="Tracks", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [12]:
# Descriptive analysis for 'artist' column
display(HTML(f"> Most frequent data value within ['artist'] column: <b>{df_music_clean.loc[(df_music_clean['artist'] != 'unknown'), 'artist'].mode()[0]}</b>"))

In [13]:
df_music_clean['artist'].value_counts()

artist
unknown               5854
kartvelli              127
malfa                  109
real_bodrit             90
the_seasons             79
                      ...
outlandish               1
king_hot                 1
david_erwin              1
om_ovnimoon              1
marianne_faithfull       1
Name: count, Length: 37676, dtype: int64

In [14]:
# Histogram for 'artist' column
plot_cualitative_histogram_plotlypx(df_music_clean.loc[(df_music_clean['artist'] != 'unknown'), 'artist'], color="grey", title="Histogram for ['artist'] column", xlabel="Artists", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [15]:
# Descriptive analysis for 'genre' column
display(HTML(f"> Most frequent data value within ['genre'] column: <b>{df_music_clean['genre'].mode()[0]}</b>"))

In [16]:
df_music_clean['genre'].value_counts()

genre
pop              8176
dance            6334
rock             5769
electronic       5518
hiphop           3020
                 ...
specialty           1
taraftar            1
tanzorchester       1
synthpop            1
acid                1
Name: count, Length: 264, dtype: int64

In [17]:
# Histogram for 'genre' column
plot_cualitative_histogram_plotlypx(df_music_clean['genre'], color="grey", title="Histogram for ['genre'] column", xlabel="Genres", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [18]:
# Descriptive analysis for 'city' column
display(HTML(f"> Most frequent data value within ['city'] column: <b>{df_music_clean['city'].mode()[0]}</b>"))

In [19]:
df_music_clean['city'].value_counts()

city
springfield    41854
shelbyville    18108
Name: count, dtype: int64

In [20]:
# Histogram for 'city' column
plot_cualitative_histogram_plotlypx(df_music_clean['city'], color="grey", title="Histogram for ['city'] column", xlabel="Cities", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=0, rotation_y=0, top_n=None)

In [21]:
# Descriptive analysis for 'time' column
display(HTML(f"> Most frequent data value within ['time'] column: <b>{df_music_clean['time'].mode()[0]}</b>"))

In [22]:
df_music_clean['time'].value_counts()

time
21:51:22    12
09:25:10    12
08:14:07    12
20:29:42    11
20:18:55    10
            ..
14:05:30     1
14:38:30     1
13:21:33     1
20:03:28     1
13:56:26     1
Name: count, Length: 20299, dtype: int64

In [23]:
# Histogram for 'time' column
plot_cualitative_histogram_plotlypx(df_music_clean['time'], color="grey", title="Histogram for ['time'] column", xlabel="Time", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=90, rotation_y=0, top_n=70)

In [24]:
# Descriptive analysis for 'day' column
display(HTML(f"> Most frequent data value within ['day'] column: <b>{df_music_clean['day'].mode()[0]}</b>"))

In [25]:
df_music_clean['day'].value_counts()

day
friday       21464
monday       20792
wednesday    17706
Name: count, dtype: int64

In [26]:
# Histogram for 'day' column
plot_cualitative_histogram_plotlypx(df_music_clean['day'], color="grey", title="Histogram for ['day'] column", xlabel="Days", 
                                    ylabel="Frequency", figsize=(1200, 600), xtick=None, ytick=None, rotation_x=0, rotation_y=0, top_n=None)

In [27]:
# Joint Frequency City vs Genre
ct_city_genre = pd.crosstab(df_music_clean['city'], df_music_clean['genre'])
ct_city_genre

genre,acid,acoustic,action,adult,africa,afrikaans,alternative,ambient,americana,animated,...,unknown,urban,uzbek,variete,vi,videogame,vocal,western,world,worldbeat
city,,,,,,,,,,,,,,,,,,,,,
shelbyville,0,2,0,8,4,0,635,64,1,0,...,120,76,12,14,1,48,24,33,509,1
springfield,1,3,4,16,12,4,1358,183,7,2,...,344,158,16,24,2,66,65,64,1425,1

In [28]:
# Normalized Joint Frequency City vs Genre (proportions)
ctp_city_genre = pd.crosstab(df_music_clean['city'], df_music_clean['genre'], normalize="index")
ctp_city_genre

genre,acid,acoustic,action,adult,africa,afrikaans,alternative,ambient,americana,animated,...,unknown,urban,uzbek,variete,vi,videogame,vocal,western,world,worldbeat
city,,,,,,,,,,,,,,,,,,,,,
shelbyville,0.000000,0.000110,0.000000,0.000442,0.000221,0.000000,0.035067,0.003534,0.000055,0.000000,...,0.006627,0.004197,0.000663,0.000773,0.000055,0.002651,0.001325,0.001822,0.028109,0.000055
springfield,0.000024,0.000072,0.000096,0.000382,0.000287,0.000096,0.032446,0.004372,0.000167,0.000048,...,0.008219,0.003775,0.000382,0.000573,0.000048,0.001577,0.001553,0.001529,0.034047,0.000024

In [29]:
plot_crosstab_bars_plotlypx(ct_city_genre.loc[:, ct_city_genre.max(axis=0) > 100], colors=px.colors.sequential.Greys, figsize=(1200, 600), title='Joint Frequency City vs Genre', xlabel=None, ylabel=None, rotation_x=0, rotation_y=0)

In [30]:
# Joint Frequency City vs Day
ct_city_day = pd.crosstab(df_music_clean['city'], df_music_clean['day'])
ct_city_day

day          friday  monday  wednesday
city
shelbyville    5784    5461       6863
springfield   15680   15331      10843

In [31]:
# Normalized Joint Frequency City vs Day (proportions)
ctp_city_day = pd.crosstab(df_music_clean['city'], df_music_clean['day'], normalize="index")
ctp_city_day

day            friday    monday  wednesday
city
shelbyville  0.319417  0.301579   0.379004
springfield  0.374636  0.366297   0.259067

In [32]:
plot_crosstab_bars_plotlypx(ct_city_day, colors=px.colors.sequential.Greys, figsize=(1200, 600), title='Joint Frequency City vs Day', xlabel=None, ylabel=None, rotation_x=0, rotation_y=0)

#### **4.1.2** Descriptive statistics for Quantitative Data

**4.1.2.1** Central trend evaluation

In [33]:
# Show global central trend
for column in df_music_location.columns:
    if column == 'city' or column == 'userid':
        continue
    else:
        evaluate_central_trend(df_music_location, column)
        print()

In [34]:
plotly_frequency_density_numeric_plotlypx(df_music_location['tracks'], bins=50, density=False, color='grey', title='Global Tracks Distribution', xlabel='Tracks', ylabel='Frequency/Density',
                                          xticks_range=(0, 50, 1), rotation=0, show_kde=False)

In [35]:
plotly_frequency_density_numeric_plotlypx(df_music_location['artists'], bins=40, density=False, color='grey', title='Global Artists Distribution', xlabel='Artists', ylabel='Frequency/Density',
                                          xticks_range=(0, 40, 1), rotation=0, show_kde=False)

In [36]:
plotly_frequency_density_numeric_plotlypx(df_music_location['genres'], bins=18, density=False, color='grey', title='Global Genres Distribution', xlabel='Genres', ylabel='Frequency/Density',
                                          xticks_range=(0, 18, 1), rotation=0, show_kde=False)

In [37]:
number_day = {'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6, 'Sunday': 7}
df_music_loc_dt['day'] = df_music_loc_dt['day'].str.title().map(number_day)
df_music_loc_dt

              city    userid  day  hour  tracks  artists  genres
0      shelbyville  100173ED    3    20       1        1       1
1      shelbyville  10089377    1    20       1        1       1
2      shelbyville  10089377    3    21       2        2       2
3      shelbyville  10101201    3    14       2        2       2
4      shelbyville  101861D1    1    20       2        2       2
...            ...       ...  ...   ...     ...      ...     ...
49839  springfield  FFF92382    1     9       1        1       1
49840  springfield  FFF965B2    1    13       1        1       1
49841  springfield  FFF965B2    1    14       1        1       1
49842  springfield   FFFBB52    1    20       4        4       4
49843  springfield   FFFD03A    5    20       1        1       1

[49844 rows x 7 columns]

In [38]:
# Show global datetime central trend
for column in df_music_loc_dt.columns:
    if column == 'city' or column == 'userid':
        continue
    else:
        evaluate_central_trend(df_music_loc_dt, column)
        print()

In [39]:
plotly_frequency_density_numeric_plotlypx(df_music_loc_dt['day'], bins=7, density=False, color='grey', title='Global Tracks Distribution By Day', xlabel='Days', ylabel='Frequency/Density',
                                          xticks_range=(1,7,1), rotation=0, show_kde=False)

In [40]:
plotly_frequency_density_numeric_plotlypx(df_music_loc_dt['hour'], bins=24, density=False, color='grey', title='Global Tracks Distribution By Hour', xlabel='Hours', ylabel='Frequency/Density',
                                          xticks_range=(0, 24, 1), rotation=0, show_kde=False)

**4.1.2.3** Correlations

In [41]:
# Generate a correlation Matrix
# pearson: linear, spearman: monotonic (more robust to outliers), kendall: non-parametric, stricter
corr_matrix = df_music_loc_dt.corr(method='pearson', numeric_only=True).round(3)
corr_matrix

           day   hour  tracks  artists  genres
day      1.000 -0.003  -0.001   -0.001  -0.001
hour    -0.003  1.000   0.022    0.021   0.024
tracks  -0.001  0.022   1.000    0.966   0.822
artists -0.001  0.021   0.966    1.000   0.842
genres  -0.001  0.024   0.822    0.842   1.000

In [42]:
plot_scatter_matrix_plotlypx(df_music_loc_dt)

## __5. Insights__

### 🎯 Statistical Findings

- **High Variability Across Day, Hour, Genre, Artist, Tracks**:  
  Coefficient of Variation (CV) highlights notable variability in activity patterns. Making mean be misleading, recommending to use Median as
  reference central value.

- **Segmentation**:  
  Day and hour show a clear segmentation pattern in music activity, indicating that the resulting groups should be further analyzed.

- **Correlation**:  
  The strong correlation between Genre, Track, and Artist reflects genre specialization: most artists concentrate their catalog within a single genre, which can simplify user segmentation and recommendation models

### 🎯 Preliminary Business Findings

- **Most Frequent Played Track, Artist, Genre**:   
  Track: 'brand'   
  Artist: 'kartvelli'   
  Genre: 'pop'   

- **Location Music Activity**:
  Springfield stands out with higher levels of music activity than Spriengfield, suggesting stronger audience engagement in that area.

- **Date And Time Music Activity**:
  Music consumption peaks in the Afternoon and reaches its highest levels on Fridays, suggesting strong end-of-week engagement.

- **Trends in music genres across locations**:
  While Springfield and Shelbyville show different levels of music activity, both exhibit similar preferences in genres, mainly Pop, Dance, Electronic, and Rock.

  ***Note**:
  These findings are preliminary. Accounting for outliers and performing additional data segmentation will help achieve clearer and more reliable insights.